channels:
  - conda-forge
dependencies:
  - ffmpeg
  - ffprobe
  - python
  - jupyter-server-proxy
  - jupyterlab-git
  - pip:
      - jupyter-contrib-nbextensions
      - pydub 
      - shazamio
      - spotipy
      - tabulate
      - tqdm
      - youtube_dl